/**
 * Babees Place demo catalog — 5 categories, 50 products.
 * Adapted to live schema: no SKU/rating/reviews columns.
 * slug doubles as stable product code (e.g. bp-fsh-001).
 * discount_price = compare-at / sale price when set.
 * Product media: curated CDN URLs from media-map.mjs (primary + gallery + thumb + alt).
 */

import { mediaForSlug } from './media-map.mjs';

export const CATEGORIES = [
  {
    id: 'a1000000-0000-4000-8000-000000000001',
    name: 'Fashion',
    slug: 'fashion',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000002',
    name: 'Electronics',
    slug: 'electronics',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000003',
    name: 'Home & Living',
    slug: 'home-living',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000004',
    name: 'Toys & Kids',
    slug: 'toys-kids',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000005',
    name: 'Beauty & Accessories',
    slug: 'beauty-accessories',
  },
];

const FASHION = 'a1000000-0000-4000-8000-000000000001';
const ELECTRONICS = 'a1000000-0000-4000-8000-000000000002';
const HOME = 'a1000000-0000-4000-8000-000000000003';
const TOYS = 'a1000000-0000-4000-8000-000000000004';
const BEAUTY = 'a1000000-0000-4000-8000-000000000005';

function product(n, fields) {
  const num = String(n).padStart(3, '0');
  const prefix = fields.codePrefix;
  const slug = `${prefix}-${num}`;
  // Schema: price = regular; discount_price = sale (must be <= price).
  // Fields may pass compare_price (higher) + price (selling).
  const regular = fields.compare_price ?? fields.price;
  const sale = fields.compare_price != null ? fields.price : (fields.discount_price ?? null);
  const discount =
    sale != null && Number(sale) < Number(regular) ? Number(sale) : null;
  const media = mediaForSlug(slug, fields.name);
  return {
    id: `a2000000-0000-4000-8000-${String(n).padStart(12, '0')}`,
    slug,
    is_active: true,
    image_url: media.image_url,
    images: media.images,
    name: fields.name,
    description: fields.description,
    category_id: fields.category_id,
    category: fields.categoryLabel,
    price: Number(regular),
    discount_price: discount,
    stock: fields.stock,
    featured: Boolean(fields.featured),
  };
}

/** Exactly 50 products */
export const PRODUCTS = [
  // —— Fashion (15) ——
  product(1, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Essential Cotton Tee — White',
    description: 'Soft crew-neck t-shirt in breathable cotton. Everyday fit for Nairobi weather.',
    price: 890,
    stock: 72,
    featured: true,
    image: 'tee-white.jpg',
  }),
  product(2, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Graphic Tee — City Lines',
    description: 'Relaxed-fit tee with a subtle city print. Pre-shrunk cotton blend.',
    price: 1200,
    compare_price: 1490,
    stock: 45,
    image: 'tee-graphic-navy.jpg',
  }),
  product(3, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Fleece Hoodie — Charcoal',
    description: 'Mid-weight fleece hoodie with kangaroo pocket and drawstring hood.',
    price: 2890,
    stock: 38,
    featured: true,
    image: 'hoodie-charcoal.jpg',
  }),
  product(4, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Zip Hoodie — Olive',
    description: 'Full-zip hoodie with ribbed cuffs. Ideal for cool evenings.',
    price: 3200,
    stock: 28,
    image: 'hoodie-olive.jpg',
  }),
  product(5, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Light Bomber Jacket — Black',
    description: 'Water-resistant bomber with a clean silhouette and inner pocket.',
    price: 4500,
    compare_price: 5200,
    stock: 18,
    featured: true,
    image: 'jacket-bomber-black.jpg',
  }),
  product(6, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Denim Jacket — Classic Blue',
    description: 'Stone-washed denim jacket with metal buttons and chest pockets.',
    price: 3990,
    stock: 22,
    image: 'jacket-denim-blue.jpg',
  }),
  product(7, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Slim Fit Jeans — Indigo',
    description: 'Stretch denim slim jeans with a mid rise and clean finish.',
    price: 2790,
    stock: 54,
    image: 'jeans-indigo.jpg',
  }),
  product(8, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Straight Jeans — Washed Grey',
    description: 'Straight-leg jeans in a soft washed grey. Comfortable all-day wear.',
    price: 2590,
    stock: 41,
    image: 'jeans-grey.jpg',
  }),
  product(9, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Linen Midi Dress — Sand',
    description: 'Breathable linen-blend midi dress with a soft A-line cut.',
    price: 3490,
    stock: 16,
    featured: true,
    image: 'dress-sand.jpg',
  }),
  product(10, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Shirt Dress — Navy Stripe',
    description: 'Button-front shirt dress with side pockets and a removable belt.',
    price: 3290,
    stock: 14,
    image: 'dress-navy-stripe.jpg',
  }),
  product(11, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Urban Runner Sneakers — White',
    description: 'Lightweight sneakers with cushioned soles for daily walks and commute.',
    price: 4200,
    stock: 33,
    featured: true,
    image: 'sneakers-white.jpg',
  }),
  product(12, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Court Sneakers — Black/Gum',
    description: 'Low-top court sneakers with gum sole and padded collar.',
    price: 3990,
    compare_price: 4590,
    stock: 7,
    image: 'sneakers-black-gum.jpg',
  }),
  product(13, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Leather Slide Sandals — Tan',
    description: 'Open-toe leather slides with a contoured footbed.',
    price: 1890,
    stock: 40,
    image: 'sandals-tan.jpg',
  }),
  product(14, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Canvas Crossbody Bag — Khaki',
    description: 'Compact crossbody with adjustable strap and zippered main pocket.',
    price: 1650,
    stock: 29,
    image: 'bag-crossbody-khaki.jpg',
  }),
  product(15, {
    codePrefix: 'bp-fsh',
    category_id: FASHION,
    categoryLabel: 'Fashion',
    name: 'Structured Cap — Black',
    description: 'Six-panel cotton cap with embroidered Babees mark.',
    price: 990,
    stock: 65,
    image: 'cap-black.jpg',
  }),

  // —— Electronics (10) ——
  product(16, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Wireless Earbuds — Pearl White',
    description: 'True wireless earbuds with charging case and clear call mic.',
    price: 2999,
    compare_price: 3499,
    stock: 48,
    featured: true,
    image: 'earbuds-white.jpg',
  }),
  product(17, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Bluetooth Speaker — Midnight',
    description: 'Portable speaker with rich bass and 10-hour battery life.',
    price: 4500,
    stock: 26,
    featured: true,
    image: 'speaker-midnight.jpg',
  }),
  product(18, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Power Bank 20,000 mAh',
    description: 'Dual-output power bank with fast charge support for phones and tablets.',
    price: 3200,
    stock: 55,
    image: 'powerbank-20000.jpg',
  }),
  product(19, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'USB-C Fast Phone Charger 30W',
    description: 'Compact wall charger with USB-C PD for modern smartphones.',
    price: 1490,
    stock: 80,
    image: 'charger-usbc-30w.jpg',
  }),
  product(20, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Smart Watch — Active Fit',
    description: 'Fitness smart watch with heart-rate tracking and message alerts.',
    price: 6500,
    stock: 21,
    featured: true,
    image: 'smartwatch-active.jpg',
  }),
  product(21, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Wireless Mouse — Graphite',
    description: 'Quiet-click wireless mouse with USB receiver and long battery life.',
    price: 1290,
    stock: 62,
    image: 'mouse-graphite.jpg',
  }),
  product(22, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'USB-C Hub 7-in-1',
    description: 'HDMI, USB-A, SD, and charging passthrough for laptops on the go.',
    price: 3890,
    stock: 19,
    image: 'usb-hub-7in1.jpg',
  }),
  product(23, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Aluminium Laptop Stand',
    description: 'Adjustable laptop stand that improves posture and cooling.',
    price: 2490,
    stock: 34,
    image: 'laptop-stand-silver.jpg',
  }),
  product(24, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'Portable Desk Fan — Mini',
    description: 'USB-powered portable fan with three speeds for desk or travel.',
    price: 990,
    stock: 6,
    image: 'fan-portable-mini.jpg',
  }),
  product(25, {
    codePrefix: 'bp-elc',
    category_id: ELECTRONICS,
    categoryLabel: 'Electronics',
    name: 'LED Desk Lamp — Warm White',
    description: 'Touch-dimmable LED desk lamp with flexible arm and USB power.',
    price: 2190,
    stock: 30,
    image: 'desk-lamp-led.jpg',
  }),

  // —— Home & Living (10) ——
  product(26, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Woven Storage Basket — Large',
    description: 'Sturdy woven basket for blankets, toys, or laundry overflow.',
    price: 1890,
    stock: 27,
    image: 'basket-storage-large.jpg',
  }),
  product(27, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Throw Pillow Cover — Terracotta',
    description: 'Soft cushion cover with hidden zip. Insert sold separately.',
    price: 890,
    stock: 50,
    image: 'pillow-terracotta.jpg',
  }),
  product(28, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Silent Wall Clock — Oak Frame',
    description: 'Quiet quartz wall clock with a warm oak-look frame.',
    price: 1590,
    stock: 23,
    image: 'clock-oak.jpg',
  }),
  product(29, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Collapsible Laundry Basket',
    description: 'Space-saving laundry basket that folds flat when not in use.',
    price: 1290,
    stock: 36,
    image: 'laundry-basket-grey.jpg',
  }),
  product(30, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Ceramic Coffee Mug Set (4)',
    description: 'Four stackable stoneware mugs in mixed earth tones.',
    price: 1790,
    stock: 42,
    image: 'mugs-set-4.jpg',
  }),
  product(31, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Kitchen Drawer Organizer',
    description: 'Adjustable bamboo organizer for cutlery and utensils.',
    price: 1450,
    stock: 31,
    image: 'kitchen-organizer.jpg',
  }),
  product(32, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Cotton Bed Sheet Set — Queen',
    description: 'Breathable cotton sheet set with pillowcases. Soft wash finish.',
    price: 3990,
    compare_price: 4590,
    stock: 17,
    image: 'bedsheet-queen-cream.jpg',
  }),
  product(33, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Insulated Water Bottle 750ml',
    description: 'Stainless bottle that keeps drinks cold for hours. Leak-resistant lid.',
    price: 1690,
    stock: 58,
    image: 'bottle-750-steel.jpg',
  }),
  product(34, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Food Storage Containers (6-Pack)',
    description: 'Airtight containers in nested sizes for meal prep and leftovers.',
    price: 2100,
    stock: 39,
    image: 'containers-food-6.jpg',
  }),
  product(35, {
    codePrefix: 'bp-hom',
    category_id: HOME,
    categoryLabel: 'Home & Living',
    name: 'Desk Organizer Tray',
    description: 'Multi-compartment desk tray for pens, chargers, and sticky notes.',
    price: 990,
    stock: 44,
    image: 'desk-organizer.jpg',
  }),

  // —— Toys & Kids (8) ——
  product(36, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Wooden Building Blocks (60 pcs)',
    description: 'Smooth wooden blocks in bright colours for open-ended play.',
    price: 2490,
    stock: 25,
    image: 'blocks-wood-60.jpg',
  }),
  product(37, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Stuffed Bear — Honey',
    description: 'Soft plush bear with embroidered eyes. Suitable for ages 3+.',
    price: 1290,
    stock: 47,
    image: 'bear-stuffed-honey.jpg',
  }),
  product(38, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Remote Control Car — Rally',
    description: 'Rechargeable RC car with responsive controls for indoor/outdoor fun.',
    price: 3590,
    stock: 15,
    image: 'rc-car-rally.jpg',
  }),
  product(39, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Family Puzzle Set — 500 pcs',
    description: 'Colourful 500-piece puzzle with a sturdy poster guide.',
    price: 1190,
    stock: 33,
    image: 'puzzle-500.jpg',
  }),
  product(40, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Educational Flash Cards',
    description: 'Alphabet and number cards for early learning at home.',
    price: 650,
    stock: 70,
    image: 'cards-educational.jpg',
  }),
  product(41, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Play Kitchen Set — Mini Chef',
    description: 'Compact play kitchen with pots, utensils, and clickable knobs.',
    price: 4990,
    stock: 9,
    image: 'kitchen-toy-set.jpg',
  }),
  product(42, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Junior Basketball Size 5',
    description: 'Durable indoor/outdoor basketball sized for kids and teens.',
    price: 1890,
    stock: 28,
    image: 'basketball-size5.jpg',
  }),
  product(43, {
    codePrefix: 'bp-toy',
    category_id: TOYS,
    categoryLabel: 'Toys & Kids',
    name: 'Skipping Rope — Adjustable',
    description: 'Adjustable skipping rope with comfortable foam grips.',
    price: 450,
    stock: 85,
    image: 'rope-skipping.jpg',
  }),

  // —— Beauty & Accessories (7) ——
  product(44, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Everyday Backpack — Slate',
    description: 'Padded laptop sleeve backpack with water-resistant exterior.',
    price: 3490,
    stock: 32,
    image: 'backpack-slate.jpg',
  }),
  product(45, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Leather Wallet — Cognac',
    description: 'Slim bifold wallet in genuine leather with RFID card slots.',
    price: 2290,
    stock: 24,
    image: 'wallet-cognac.jpg',
  }),
  product(46, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Polarized Sunglasses — Tortoise',
    description: 'UV400 polarized lenses in a lightweight tortoise frame.',
    price: 1990,
    compare_price: 2490,
    stock: 20,
    image: 'sunglasses-tortoise.jpg',
  }),
  product(47, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Shea Body Lotion 400ml',
    description: 'Daily moisturising lotion with shea butter for dry skin.',
    price: 890,
    stock: 60,
    image: 'lotion-shea-400.jpg',
  }),
  product(48, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Gentle Care Shampoo 350ml',
    description: 'Sulphate-free shampoo for everyday cleansing and softness.',
    price: 750,
    stock: 68,
    image: 'shampoo-gentle-350.jpg',
  }),
  product(49, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Foaming Face Cleanser 150ml',
    description: 'Mild foaming cleanser that removes oil without stripping skin.',
    price: 980,
    stock: 52,
    image: 'cleanser-foam-150.jpg',
  }),
  product(50, {
    codePrefix: 'bp-bty',
    category_id: BEAUTY,
    categoryLabel: 'Beauty & Accessories',
    name: 'Weekend Travel Bag — Navy',
    description: 'Duffel-style travel bag with shoe compartment and shoulder strap.',
    price: 4290,
    stock: 13,
    image: 'travel-bag-navy.jpg',
  }),
];

export const PRODUCT_IDS = PRODUCTS.map((p) => p.id);

export const PICKUP_LOCATIONS = [
  {
    id: 'a3000000-0000-4000-8000-000000000001',
    name: 'Babees Place — Westlands Hub',
    building: 'Sarit Centre, Ground Floor Collection Point',
    description: 'Weekday pickup 10:00–19:00. Bring your order SMS.',
    operating_hours: {
      mon_fri: '10:00-19:00',
      sat: '10:00-17:00',
      sun: 'closed',
    },
    is_active: true,
  },
  {
    id: 'a3000000-0000-4000-8000-000000000002',
    name: 'Babees Place — CBD Counter',
    building: 'Kencom House, Mezzanine',
    description: 'Central Nairobi pickup desk near Kencom bus stage.',
    operating_hours: {
      mon_fri: '09:00-18:00',
      sat: '09:00-14:00',
      sun: 'closed',
    },
    is_active: true,
  },
  {
    id: 'a3000000-0000-4000-8000-000000000003',
    name: 'Babees Place — Rongai Lockers',
    building: 'Galleria Mall service corridor',
    description: 'Self-serve lockers. Code sent when order is ready.',
    operating_hours: {
      mon_sun: '08:00-20:00',
    },
    is_active: true,
  },
];
